### ISSUE TITLE
about URPC2019 data problem

### ISSUE THREAD

**Issue by jonyzhang2023** [mousecpn/DG-YOLO#4]
Hi i notice that the label of URPC2019 (which you shared on your repo) is very small.
It is hard for me to change it to my dataset.
Why those nums so small? 
Is these divide by weight/height?

for example:
4 0.058854166666666666 0.21296296296296297 0.1171875 0.13425925925925927
2 0.190625 0.46296296296296297 0.09479166666666666 0.13425925925925927

i hope you could help me this, or we can communicate on wechat. :)

**Comment by mousecpn** [comment]
Yes, the first number is the label, and the following four are the [x,y,w,h], which are divided by width/height/

**Comment by jonyzhang2023** [comment]
cool, i have finished this problem. thx!
btw, could i email you for communicating?

**Comment by mousecpn** [comment]
pinhaosong@pku.edu.cn

> cool, i have finished this problem. thx! btw, could i email you for communicating?
